import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Employee } from '../../shared/models';
import { EmployeeService } from '../../core/services/employee-service';


@Component({
  selector: 'app-employee',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './employee.html',
  styleUrl: './employee.css',
})
export class EmployeeComponent implements OnInit {

  // Employee List
  employees: Employee[] = [];

  // Form Model
  employee: Employee = {
    firstName: '',
    lastName: '',
    email: '',
    department: '',
    designation: '',
    joiningDate: '',
    status: 'Active',
  };

  isEdit = false;

  constructor(private employeeService: EmployeeService,private cdr:ChangeDetectorRef) {}

  ngOnInit(): void {
    this.getEmployees();
  }

  // GET ALL EMPLOYEES
  getEmployees(): void {
    this.employeeService.getEmployees().subscribe({
      next: (res) => {
        this.employees = res;
        this.cdr.markForCheck();
      },
      error: (err) => {
        console.log(err);
      },
    });
  }

  // ADD EMPLOYEE
  addEmployee(): void {
    // id auto generated by json-server
    this.employeeService.addEmployee(this.employee).subscribe({
      next: () => {
        this.getEmployees();
        this.resetForm();
       console.log(this.employee);
        
      },
      error: (err) => {
        console.log(err);
      },
    });
  }

  // EDIT EMPLOYEE
  editEmployee(emp: Employee): void {
    this.employee = { ...emp };
    this.isEdit = true;
  }

  // UPDATE EMPLOYEE
  updateEmployee(): void {
    if (!this.employee.id) return;

    this.employeeService
      .updateEmployee(this.employee.id, this.employee)
      .subscribe({
        next: () => {
          this.getEmployees();
          this.resetForm();
          this.isEdit = false;
        },
        error: (err) => {
          console.log(err);
        },
      });
  }

  // DELETE EMPLOYEE
  deleteEmployee(id?: string): void {
    if (!id) return;

    this.employeeService.deleteEmployee(id).subscribe({
      next: () => {
        this.getEmployees();
      },
      error: (err) => {
        console.log(err);
      },
    });
  }

  // RESET FORM
  resetForm(): void {
    this.employee = {
      firstName: '',
      lastName: '',
      email: '',
      department: '',
      designation: '',
      joiningDate: '',
      status: 'Active',
    };
  }
}